### ISSUE TITLE
按群名查找的风险

### ISSUE THREAD

**Issue by bigbrother666sh** [ShanghaiITVolunteer/AntigenWechatBot#11]
antigen_bot/message_forward.py
```
        room_topics: List[str] = self.user2rooms.get(talker.contact_id, [])
        for room_topic in room_topics:
            room = await self.bot.Room.find(room_topic)
```
用room_topic索引会不会有问题，群名一致的情况？

**Comment by wj-Mcat** [comment]
如果两个群名是一致的话，肯定会存在问题，可是`user2rooms`的值建议保存`room_id`即可解决这个问题。

所以这个问题转化成了：前期使用room-topic来保存，后期可以将room-topic转化成room-id就可以解决问题了。

**Comment by bigbrother666sh** [comment]
我昨晚已经就是全部切换到存储room_id了。
