### ISSUE TITLE
msg.forward(room) 的风险

### ISSUE THREAD

**Issue by bigbrother666sh** [ShanghaiITVolunteer/AntigenWechatBot#12]
antigen_bot/message_forward.py

我试下来，对接padlocal协议，仅能forward 文本信息。
但目前看来至少小程序、url 还是需要的

**Comment by wj-Mcat** [comment]
我昨天测试：小程序、URL、图片等都可以转发的。

如果你用这个代码还是有问题的话，我们待会儿可以来一个10 min quick video 来测试一下。

**Comment by bigbrother666sh** [comment]
那部署后看吧，我这里之前对接padlocal是有问题的，媒体类甚至用msg to_filebox出来的对象直接发送都不行（转存本地，再从本地文件生成fileboxh是可以的）

**Comment by wj-Mcat** [comment]
媒体类的消息建议直接转发，不要保存到本地，这样就直接使用微信自带的转发机制，避免中间存在一些由于存储带来的问题。
